<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_group_member_order_detail  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["AfterAdd"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, &$pageObject)
{

		

$data = array();
$data["group_member_id"] = "1";
$data["member_id"] = $_SESSION["member_id"];
$data["group_id"] = $_SESSION["group_id"];
$data["order_date"] = NOW();
$data["valid"] = "0";
$data["currency"] = "1";
DB::Insert("group_member_order", $data );

$data = array();
$keyvalues = array();
$data["group_member_order_id"] = "1";
$data["group_member_id"] = "1";
$data["member_id"] = $_SESSION["member_id"];
$data["group_id"] = $_SESSION["group_id"];
$data["group_product_id"] = "1";
$data["nominal"] = "1";
$data["quantity"] = $values["quantity"];
$data["total"] = "1";
$data["progress"] = "0";
$keyvalues["group_member_order_detail_id"] = $values["group_member_order_detail_id"];
DB::Update("group_member_order_detail", $data, $keyvalues );

$data = array();
$keyvalues = array();
$data["total"] = "1";
$keyvalues["group_member_order_id"] = $values["group_member_order_id"];
DB::Update("group_member_order", $data , $keyvalues);



// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
